ManageIQ/manageiq-providers-workflows

config/settings.yml
lib/manageiq/providers/workflows.rb

Add setting to enable/disable the workflows prototype provider

Add a prototype/ems_workflows/enabled Setting

---

app/models/manageiq/providers/workflows/automation_manager.rb
app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Depends:
https://github.com/ManageIQ/manageiq/issues/22311

Use ConfigurationScripts for Workflows

---

app/models/manageiq/providers/workflows/automation_manager.rb
app/models/manageiq/providers/workflows/automation_manager/scm_credential.rb

Add SCM Credentials for Workflows Repositories
Depends on:

Add Workflows SCM Credential for Repositories

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb

Invoke service before after callbacks

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
manageiq-providers-workflows.gemspec
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Move workflow executing into manageiq-floe

---

config/settings/development.yml
lib/manageiq/providers/workflows/engine.rb

a developer setting to run the various runners

Add Settings.ems.ems_workflows.runner

---

lib/manageiq/providers/workflows/engine.rb
manageiq-providers-workflows.gemspec

Use the new interface added by https://github.com/ManageIQ/floe/pull/169
TODO:

Update to use Floe.register_scheme API

---

lib/manageiq/providers/workflows.rb
lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_runner.rb

Depends on:
Example ASL file
```
{
"Comment": "An example of using the builtin scheme.",
"StartAt": "FirstState",
"States": {
"FirstState": {
"Type": "Task",
"Resource": "builtin://email",
"Parameters": {
"To": "adam@grare.com",
"From": "adam@grare.com",
"Subject": "Hello, world"
},
"Next": "SuccessState"
},
"SuccessState": {
"Type": "Succeed"
}
}
}
```

Add Builtin Runner with Email example method

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb

pass object to workflow instance

---

lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_runner.rb

dependency:
status: sharing my current code

Add builtin method: provision_execute

---

lib/manageiq/providers/workflows/builtin_methods.rb

Improve BuiltinMethods.provision_execute error checking

---

lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_result_mixin.rb
lib/manageiq/providers/workflows/builtin_runner.rb
spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
spec/lib/manageiq/providers/workflows/builtin_runner_spec.rb

Add specs for BuiltinMethods

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb

We should not ship invalid workflows, so raise an exception when seeding fails.
@agrare Please review.  Related to https://github.com/ManageIQ/manageiq/pull/23048, but doesn't really depend on it.

Fail seeding on invalid out of the box workflows.

---

lib/manageiq/providers/workflows/builtin_methods.rb
spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb

Default email from

---

lib/manageiq/providers/workflows/builtin_methods.rb
spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb

Follow-up to https://github.com/ManageIQ/manageiq-providers-workflows/pull/86

Check that the requested configuration_script_payload record is an EmbeddedAnsible Playbook

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
config/settings.yml
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Drop workflows prototype settings

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
manageiq-providers-workflows.gemspec
spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

Floe switched to enforcing workflow input and output is JSON so we need to update our callers here

Bump floe to v0.12.0

---

manageiq-providers-workflows.gemspec

Pull in floe v0.13.0 https://github.com/ManageIQ/floe/releases/tag/v0.13.0

Bump floe to v0.13.0 for Intrinsic Functions

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_runner.rb
spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
spec/lib/manageiq/providers/workflows/builtin_runner_spec.rb

I needed this for a demo
This allows us to send an email to the requester from a workflow

Pass requester userid and email into workflows

---

lib/manageiq/providers/workflows/runner.rb

Workflows Runner event log should be debug

---

manageiq-providers-workflows.gemspec

Pull in support for Map / Parallel https://github.com/ManageIQ/floe/releases/tag/v0.15.0

Update floe to v0.15.0

---

manageiq-providers-workflows.gemspec

Bump floe to v0.16.0 for ItemBatcher support

---

lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_runner.rb
spec/lib/manageiq/providers/workflows/builtin_runner_spec.rb

This looks like it was a typo back to the introduction of the class in 70d79b57 but was consistent so it was working.

Fix Typo BuiltinRunnner

---

lib/manageiq/providers/workflows/engine.rb

https://github.com/ManageIQ/manageiq/issues/23470

Change podman root containers/storage directory

---

lib/manageiq/providers/workflows/builtin_methods.rb

MiqProvision is only for VM provisioning, the parent class MiqProvisionTask supports a number of types of provisioning with the same interface which allows for workflows to be used for more types of provisioning.
Example using `provision.asl` with `ManageIQ::Providers::TerraformEnterprise::AutomationManager::Provision` which `< ::MiqProvisionTask` and is a `ConfigurationScript` type provisioning.
```
vmdb(dev)> source = ManageIQ::Providers::TerraformEnterprise::AutomationManager::ConfigurationScript.find_by(:manager_ref => 'ws-BkpXRVrXTfUNXuxT')
vmdb(dev)> config_info = {:owner_email => "adam@grare.com", :source_id => source.id, :configuration_script_payload_id => ConfigurationScriptPayload.find_by(:name => "provision.asl").id}
vmdb(dev)> request = …
```

Allow manageiq://provision_execute MiqProvisionTask
