ManageIQ/manageiq-providers-workflows

lib/manageiq-providers-workflows.rb
lib/manageiq/providers/workflows.rb
spec/spec_helper.rb

Adopt convention already supported by bundler and required by zeitwerk so we don't need to tell zeitwerk to ignore this lib/gem-name.rb file.

Drop lib/gem-name.rb in favor of lib/gem/name.rb

---

app/models/manageiq/providers/workflows/automation_manager.rb

The Embedded Workflows AutomationManager does not need EmsRefresh for anything and does not support refresh.
Follow-up:
* https://github.com/ManageIQ/manageiq/pull/22458

Disable :refresh_ems support

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

If the ems_workflows prototype flag is disabled then do not allow running workflows

Disable workflow execution if prototype disabled

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Maintain compatibility with `EmbeddedAnsible::Playbook#run`

Rename `Workflow#execute` to `#run`

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Add in the option for passing in an alternate role or a zone for the workflow to be run on.  This is important if access to resources is limited to workers running only on a certain zone.
Core PR:
* https://github.com/ManageIQ/manageiq/pull/22546

Add ability to pass zone or other role to run

---

lib/manageiq/providers/workflows.rb

This is in the background if the user hasn't set the prototype flag, so they won't realize it anyway. However, when they do enable the flag they can then hit the ground running without having to wait for a resed.
@agrare Please review.

Always allow seeding even without prototype flag

---

app/models/manageiq/providers/workflows/automation_manager/credential.rb
spec/models/manageiq/providers/workflows/automation_manager/credential_spec.rb

Creating an authentication requires defining `params_to_attributes` https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/embedded_automation_manager/authentication.rb#L28

Allow creation of Credentials for Workflows

---

app/models/manageiq/providers/workflows/automation_manager/credential.rb

Follow-up to https://github.com/ManageIQ/manageiq/pull/22570

Use params_to_attributes from core

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

Fix wrong number of arguments error from using kwargs
```
[----] E, [2023-06-15T11:14:20.330024 #734974:9740] ERROR -- evm: MIQ(MiqQueue#deliver) Message id: [9], Error: [wrong number of arguments (given 1, expected 0)]
[----] E, [2023-06-15T11:14:20.330115 #734974:9740] ERROR -- evm: [ArgumentError]: wrong number of arguments (given 1, expected 0)  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2023-06-15T11:14:20.330170 #734974:9740] ERROR -- evm: /home/grare/adam/src/manageiq/manageiq-providers-workflows/app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb:50:in `run'
/home/grare/adam/src/manageiq/manageiq/app/models/miq_queue.rb:499:in `block in dispatch_method'
```

Fix workflow_instance queue delivery

---

app/models/manageiq/providers/workflows/automation_manager/scm_credential.rb

Fix parent class for Workflows ScmCredential

---

spec/models/manageiq/providers/workflows/automation_manager/configuration_script_source_spec.rb

depends upon:
- https://github.com/ManageIQ/manageiq/pull/22614
Workflow role is no longer going to embedded ansible
(this makes the build green)

Fix workflows queued on embedded_ansible

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

After moving the state run logic into floe we no longer were setting the state output.  This was causing issues when the caller needs the output to populate e.g. a dynamic dialog dropdown.
https://github.com/ManageIQ/manageiq-providers-workflows/pull/5/files#diff-80ee5262679b29c698ee75771be7948fbfe8fcea9ff7c05ee83aaa9273d47885L89

Fix WorkflowInstance#output not being set

---

config/initializers/floe_docker_runner.rb
lib/manageiq/providers/workflows/engine.rb

Set the workflow runner based on the platform we're running on
Depends on:

Set the Floe::Workflow::Runner based on platform

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

The correct role name it "automate" not "automation", this was causing queued workflow_instances to not be picked up by Generic Workers

Fix the default role from automation to automate

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb

After_ae_deliver is expecting an automate ae_result with is "retry", "ok", or an error state: https://github.com/ManageIQ/manageiq/blob/master/app/models/service_template_provision_task.rb#L182-L195

Normalize the ae_result passed to after_ae_delivery

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

Change the Workflow#credentials format for authentication references from JSON path to `{"credential_ref" => "", "credential_field" => ""}`
Ref: https://github.com/ManageIQ/manageiq-api/pull/1231#issuecomment-1662896566

Update Workflow#credential format

---

lib/manageiq/providers/workflows/engine.rb

By default non-root images are stored in the home directory of the non-root user.  On appliances as the manageiq user this is a very small partition and not many images can be stored here.
Depends on:
https://github.com/ManageIQ/manageiq/issues/22640

Override the podman image storage root directory

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

When transforming a payload_template style hash we have to strip off the
trailing .$ after interpolating the value.

Strip trailing .$ from Credentials

---

lib/manageiq/providers/workflows/engine.rb

cc @bdunne @Fryguy I seem to recall that we agreed to create these workflow containers in our main namespace

Pass namespace to the Floe Kubernetes Runner

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Set the manageiq_api_url in the global context so that it can be referenced by workflows.

Pass manageiq_api url in global context

---

manageiq-providers-workflows.gemspec

Pull in floe v0.4.1 for fixes in task output and combined stdout/stderr on podman/docker
https://github.com/ManageIQ/floe/releases/tag/v0.4.1

Bump floe to v0.4.1 for task output fixes

---

lib/manageiq/providers/workflows/engine.rb
manageiq-providers-workflows.gemspec

@agrare @bdunne @kbrock Please review.
This PR hardcodes the value for now, but it should probably be passed down as an ENV var.  Not sure if we want to do this now or later.  @bdunne Thoughts?
Depends on 
Must be merged with

Pass the workflow service account

---

lib/manageiq/providers/workflows/engine.rb

ManageIQ::Providers::Workflows::Engine.floe_docker_runner is called in a config/initializer, which means that it is being executed in every Rails environment on boot. This includes things like `bin/rake evm:deployment_status`, which happens very early on in the orchestrator boot process.
When the orchestrator is on Kubernetes, it starts creating a Floe::Kubernetes::Runner, but then requires the new AUTOMATION_JOB_SERVICE_ACCOUNT, which doesn't exist as it is only meant to exist in the new AutomationWorker. Because of this the orchestrator fails to boot.
This commit allows that value to be nil, so it can move on. However, we should find a way to avoid creating the runner on every boot, which is a better solution.

Fix issue where new service account ENV var is forced in every process

---

manageiq-providers-workflows.gemspec

Bump floe to v0.6.0 to pull in the fixes for payload verification and ImagePull errors causing hangs on kubernetes.

Bump floe for kubernetes image pull error fixes

---

bin/before_install

Fixes issue such as:
```
After this operation, 1541 kB of additional disk space will be used.
Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.7
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.7
404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.7_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Followup to https://github.com/ManageIQ/manageiq/pull/21843

Run apt-get update before install in bin/before_install

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
manageiq-providers-workflows.gemspec
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

If a state sets a new credential then encrypt the value and update the credentials column of the workflow instance.
NOTE: currently this will set a ManageIQ::Password encrypted value in the credentials jsonb column.  If there is an existing "mapped" authentication it will create a new in-line entry in the Credentials column instead of updating the Authentication record.
Documentation:
* https://github.com/ManageIQ/manageiq-documentation/pull/1773
Fix Auth:
* https://github.com/ManageIQ/manageiq/pull/22824

Update `:credentials` column if state sets a new credential

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

If the `:credentials` column is `nil` rather than `{}` as we had been testing with, the `resolved_credentials` method properly handles this but the `update_credentials!` method was not and caused the workflow instance run to throw an exception

Handle the case where `:credentials` column is `nil`

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
manageiq-providers-workflows.gemspec
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

In the case where no credentials are mapped to a workflow, but the workflow sets a credential value the workflow was failing trying to assign a key to `nil`
Related:
* https://github.com/ManageIQ/floe/pull/156

Ensure WorkflowInstance#credentials is not nil

---

config/settings.yml
config/settings/development.yml
lib/manageiq/providers/workflows/engine.rb
manageiq-providers-workflows.gemspec

Add the ability to set runner_options in Settings

---

lib/manageiq/providers/workflows/engine.rb

Fixes
```
NoMethodError: undefined method `fetch' for #<Config::Options pull_policy="always", network="host">
/home/grare/adam/src/manageiq/manageiq-providers-workflows/lib/manageiq/providers/workflows/engine.rb:65:in `new'
/home/grare/adam/src/manageiq/manageiq-providers-workflows/lib/manageiq/providers/workflows/engine.rb:65:in `floe_docker_runner'
/home/grare/adam/src/manageiq/manageiq-providers-workflows/config/initializers/floe_docker_runner.rb:2:in `<main>'
```
Introduced by https://github.com/ManageIQ/manageiq-providers-workflows/pull/65/files#diff-90ac1f1e5e5d8f5256b8242a1bc5e74907bd131561f2c7d3bd6bf441f32d4859R63

Don't pass Config::Options in for Runner settings

---

config/initializers/floe_docker_runner.rb
lib/manageiq/providers/workflows/engine.rb
manageiq-providers-workflows.gemspec

depend upon:
This removes some knowledge of the internals of floe (but who is kidding who, we still need to know all options that each runner supports)
This also preps us for supporting multiple protocols

Use new Floe.set_runner syntax

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
app/models/manageiq/providers/workflows/automation_manager/workflow.rb
config/settings.yml
lib/manageiq/providers/workflows/engine.rb

Seed workflows from plugins' `content/workflows/**/*.asl` 
Depends on:

Seed workflows from plugins' content/workflows

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
manageiq-providers-workflows.gemspec
spec/models/manageiq/providers/workflows/automation_manager/configuration_script_source_spec.rb
spec/support/fake_workflows_repo.rb

We do something similar if you manually create a Workflow from a json payload since we don't have a file path, https://github.com/ManageIQ/manageiq-providers-workflows/blob/master/app/models/manageiq/providers/workflows/automation_manager/workflow.rb#L4 and I thought it'd add a nice "human readable" description

Set workflow description from asl comment

---

app/models/manageiq/providers/workflows/automation_manager/credential.rb

This is needed to make credential types pluggable
Needed for:
@miq-bot assign @agrare 
@miq-bot add_reviewer @agrare 
@miq-bot add_label enhancement

Add workflows credential type

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb

dependency:
- tag: v0.11.0 (already updated)
pass context into run.
This allows us to pass `_miq_request_task_id` for provisioning (and other) requests
we could probably drop the `role` parameter
Feedback:
- Do we want to set `object.class, object.id`?

Workflow#run accepts context

---

lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_runner.rb

Move the logic for checking if a method is running/successful into the BuiltinMethods so that each method can control how it checks.

Move checking builtin method status into Methods

---

lib/manageiq/providers/workflows/builtin_methods.rb
lib/manageiq/providers/workflows/builtin_runner.rb

1. Check private methods for `BuiltinRunner.respond_to?`
2. Extract `miq_task_status!` so we can reuse it for other methods
3. Add an `error_payload` method to make returning errors simpler

Some minor refactorings to BuiltinMethods / BuiltinRunner

---

lib/manageiq/providers/workflows/builtin_methods.rb

When the miq_request_task has a failure this was throwing an undefined method error
Follow-up to https://github.com/ManageIQ/manageiq-providers-workflows/pull/81

Fix BuiltinMethods.miq_request_task_status!

---

spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb

We fixed the MiqTask state to be Finished when it fails due to not having a notifier role.
https://github.com/ManageIQ/manageiq/pull/23036

Fix BuiltinMethods.email task status spec

---

lib/manageiq/providers/workflows/builtin_methods.rb
spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb

Use input to set options in the provisioning request.
This allows a workflow to manipulate the request.
- We always change the miq_request_task, even when the options have not been updated. Optionally we can add a sync parameter
- For the 2 non symbol keys, we do end up with duplicates (`nil` -> `""`, and the fqname)

automatically update options for provisioning requests

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
lib/manageiq/providers/workflows/builtin_runner.rb
spec/lib/manageiq/providers/workflows/builtin_runner_spec.rb

Built on #95 
@agrare As discussed this renames the builtin scheme to manageiq.  cc @kbrock
Co-dependent on

Rename 'builtin' scheme to 'manageiq'

---

config/settings.yml

The UI still checks for `Settings.prototype.ems_workflows.enabled` in quite a few places.  Add this back defaulted to true for backport until we can remove it from the UI.

Add back prototype workflows enabled

---

lib/manageiq/providers/workflows/engine.rb

The `Floe::ContainerRunner` looks for options with string keys where `Config::Options#to_hash` is returning symbols which means any settings being set by the user in `Settings.ems.ems_workflows.runner_options` are not being picked up by the `Floe::ContainerRunner`
I noticed this when trying to hit the API with `http://localhost:4000` with list-providers.rb and it was failing
```
=> 79:             Floe::ContainerRunner.set_runner("podman", options)
80:           when "docker"
81:             options = floe_runner_settings.docker.to_hash
82: 
83:             Floe::ContainerRunner.set_runner("docker", options)
(byebug) floe_runner_settings.podman
#<Config::Options pull_policy="always", network="host">
(byebug) options
{:pull_policy=>"always", :network=>"host"}
[12, 21] in …
```

Fix floe container_runner options not being honored

---

.rubocop_local.yml

Prevent `Style/GlobalVars- Do not introduce global variables.` rubocop warnings for `$workflows_log`

Don't warn about `$workflows_log`

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
lib/manageiq/providers/workflows/engine.rb
lib/manageiq/providers/workflows/runner.rb
manageiq-providers-workflows.gemspec
spec/lib/manageiq/providers/workflows/runner_spec.rb

Add a Workflows::Runner class which keeps a persistent thread waiting for events from Floe.  Once an event is raised we try to link the event up to a workflow and we queue a step action if we find one.
If a workflow isn't found for example if it is already completed and removed from the list then we simply continue without queueing anything.
It is common to get multiple events for a single container run so this isn't a perfect "queue step when ready" and can be more efficient but currently this is erring on the side of caution (check step_ready on every event).
Also if the worker goes down and is restarted for any reason, the typical timer-based step is still on the queue and the running workflow will be added to the runner on the next timed check.
Depends on:
Fixes …

Add event driven workflows runner

---

app/models/manageiq/providers/workflows/automation_manager/workflow.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb

Set the WorkflowInstance manager_ref as the Context.Execution.Id so that we can use it to find the WorkflowInstance more easily
Related:

Use workflow_instance manager_ref as Execution ID

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
lib/manageiq/providers/workflows/runner.rb
manageiq-providers-workflows.gemspec
spec/factories/workflow_instance.rb
spec/lib/manageiq/providers/workflows/runner_spec.rb

Use the execution_id from the docker event to lookup the workflow_instance rather than the container_ref.  Since this is static for the life of the workflow it is a much more reliable way to make the association.
Depends on:

Use WorkflowInstance#manager_ref and execution_id for events

---

spec/factories/workflow.rb
spec/factories/workflow_instance.rb

These factories were added: https://github.com/ManageIQ/manageiq/pull/22316
But were removed: https://github.com/ManageIQ/manageiq/pull/22503
They were basically NO-OP factories, so removing is no big deal
For some reason, older versions of FactoryBot were ok with a bad reference (probably because the klass was overridden anyway) But newer versions of FactoryBot complained

Remove non-existing parent factory references

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
lib/manageiq/providers/workflows/runner.rb
spec/lib/manageiq/providers/workflows/runner_spec.rb

Fix an issue where the `Workflows::Runner#docker_wait` thread queues the `workflow_instance` with `queue_args` that have `object_type`/`object_id` and not the resolved object.
`WorkflowInstance#run` looks the object up by type,id so it has the object already but `Workflows::Runner#docker_wait` only has the raw `queue_args` so it is better to allow `object_type`,`object_id` in
`WorkflowInstance#run_queue`.

Add object_type,_id to WorkflowInstance#run_queue

---

manageiq-providers-workflows.gemspec

Pull in floe v0.15.1 to fix a bug with Map/Parallel on Kubernetes/Openshift
https://github.com/ManageIQ/floe/releases/tag/v0.15.1

Fix floe bug with Parallel/Map on Kubernetes

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
spec/models/manageiq/providers/workflows/automation_manager/configuration_script_source_spec.rb
spec/support/fake_workflows_repo.rb

When syncing a repository and creating workflows check if the payload is valid and if it isn't log a (hopefully) helpful error message.
This is based on https://github.com/ManageIQ/manageiq-providers-workflows/pull/59 but instead of requiring a new column this will log the error and skip any invalid workflows.
There was also an issue with the not-implemented states raising an exception that wasn't a `Floe::InvalidWorkflowError` which would have skipped this rescue.
Example log message:
`WARN -- evm: MIQ(ManageIQ::Providers::Workflows::AutomationManager::ConfigurationScriptSource#create_workflow_from_payload) Invalid ASL file [missing_states.asl]: State Machine does not have required field "States"`

Skip invalid workflows during sync

---

config/settings.yml

The Workflows::AutomationManager doesn't have an event_catcher and thus doesn't need a blacklisted_event_names setting

Delete unused blacklisted_event_names

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

Blocked by:
Creates RequestLog records for each log entries
This way the messages will show up in The log entries on the Request screen This creates the same.
Did feel like I reinvented the wheel with the log proxy, but it seemed the simplest way.
I lifted `request_log` - with only trivial changes

Set logger for each workflow run

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb

When called from a MiqRequest object we use a `Vmdb::Loggers::RequestLogger` so that floe logs can be seen in the UI easily.  If `Floe.logger` is already a `BroadcastLogger` then `Floe.logger.wrap` isn't calling `ManageIQ::Loggers::Base#wrap` it is actually calling `ActiveSupport::BroadcastLogger#method_missing` which does `loggers.map { |logger| logger.send(name, ...) }` and results in an array being returned.
This array is then used as the `workflow.context.logger` so when we try to log to it we get `undefined method info for Array`
Introduced by https://github.com/ManageIQ/manageiq-providers-workflows/pull/128
Fixes https://github.com/ManageIQ/manageiq-providers-workflows/issues/134

Fix Logger error when called from service

---

app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb

depends:
- add interface to floe and release floe
This removes the knowledge of the context constructor and the workflow constructor It also standardizes on passing around ruby hashes and not json strings

Use workflow credentials interface

---

app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
spec/models/manageiq/providers/workflows/automation_manager/configuration_script_source_spec.rb

When syncing a repository and creating workflows check if the payload is valid and if it isn't set a (hopefully) helpful error message.
Depends on:
~~https://github.com/ManageIQ/manageiq-schema/pull/712~~
TODO:
* We don't currently check if a configuration_script_payload "supports" running, we could enable that and check for validity there and use payload_error as the unsupported reason

Check if a workflow payload is valid during sync
